// Generated by gencpp from file mobility_topic/Mobility.msg
// DO NOT EDIT!


#ifndef MOBILITY_TOPIC_MESSAGE_MOBILITY_H
#define MOBILITY_TOPIC_MESSAGE_MOBILITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobility_topic
{
template <class ContainerAllocator>
struct Mobility_
{
  typedef Mobility_<ContainerAllocator> Type;

  Mobility_()
    : ForwardY(0)
    , TurningX(0)  {
    }
  Mobility_(const ContainerAllocator& _alloc)
    : ForwardY(0)
    , TurningX(0)  {
  (void)_alloc;
    }



   typedef int8_t _ForwardY_type;
  _ForwardY_type ForwardY;

   typedef int8_t _TurningX_type;
  _TurningX_type TurningX;





  typedef boost::shared_ptr< ::mobility_topic::Mobility_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobility_topic::Mobility_<ContainerAllocator> const> ConstPtr;

}; // struct Mobility_

typedef ::mobility_topic::Mobility_<std::allocator<void> > Mobility;

typedef boost::shared_ptr< ::mobility_topic::Mobility > MobilityPtr;
typedef boost::shared_ptr< ::mobility_topic::Mobility const> MobilityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobility_topic::Mobility_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobility_topic::Mobility_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mobility_topic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mobility_topic': ['/home/nvidia/catkin_ws/src/mobility_topic/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mobility_topic::Mobility_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobility_topic::Mobility_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobility_topic::Mobility_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobility_topic::Mobility_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobility_topic::Mobility_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobility_topic::Mobility_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobility_topic::Mobility_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80c0a058aa7119b3181b6edb07201e22";
  }

  static const char* value(const ::mobility_topic::Mobility_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80c0a058aa7119b3ULL;
  static const uint64_t static_value2 = 0x181b6edb07201e22ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobility_topic::Mobility_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobility_topic/Mobility";
  }

  static const char* value(const ::mobility_topic::Mobility_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobility_topic::Mobility_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ForwardY\n\
int8 TurningX\n\
";
  }

  static const char* value(const ::mobility_topic::Mobility_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobility_topic::Mobility_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ForwardY);
      stream.next(m.TurningX);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mobility_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobility_topic::Mobility_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobility_topic::Mobility_<ContainerAllocator>& v)
  {
    s << indent << "ForwardY: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ForwardY);
    s << indent << "TurningX: ";
    Printer<int8_t>::stream(s, indent + "  ", v.TurningX);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILITY_TOPIC_MESSAGE_MOBILITY_H
