// Generated by gencpp from file multijoy/MultiJoy.msg
// DO NOT EDIT!


#ifndef MULTIJOY_MESSAGE_MULTIJOY_H
#define MULTIJOY_MESSAGE_MULTIJOY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt8.h>
#include <sensor_msgs/Joy.h>

namespace multijoy
{
template <class ContainerAllocator>
struct MultiJoy_
{
  typedef MultiJoy_<ContainerAllocator> Type;

  MultiJoy_()
    : header()
    , njoys()
    , joys()  {
    }
  MultiJoy_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , njoys(_alloc)
    , joys(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _njoys_type;
  _njoys_type njoys;

   typedef std::vector< ::sensor_msgs::Joy_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Joy_<ContainerAllocator> >::other >  _joys_type;
  _joys_type joys;





  typedef boost::shared_ptr< ::multijoy::MultiJoy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multijoy::MultiJoy_<ContainerAllocator> const> ConstPtr;

}; // struct MultiJoy_

typedef ::multijoy::MultiJoy_<std::allocator<void> > MultiJoy;

typedef boost::shared_ptr< ::multijoy::MultiJoy > MultiJoyPtr;
typedef boost::shared_ptr< ::multijoy::MultiJoy const> MultiJoyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multijoy::MultiJoy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multijoy::MultiJoy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multijoy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'multijoy': ['/home/nvidia/catkin_ws/src/multijoy/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multijoy::MultiJoy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multijoy::MultiJoy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multijoy::MultiJoy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multijoy::MultiJoy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multijoy::MultiJoy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multijoy::MultiJoy_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multijoy::MultiJoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1fe0e1be06cf2ea74daadf46387e623";
  }

  static const char* value(const ::multijoy::MultiJoy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1fe0e1be06cf2eaULL;
  static const uint64_t static_value2 = 0x74daadf46387e623ULL;
};

template<class ContainerAllocator>
struct DataType< ::multijoy::MultiJoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multijoy/MultiJoy";
  }

  static const char* value(const ::multijoy::MultiJoy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multijoy::MultiJoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/UInt8 njoys\n\
sensor_msgs/Joy[] joys\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/UInt8\n\
uint8 data\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Joy\n\
# Reports the state of a joysticks axes and buttons.\n\
Header header           # timestamp in the header is the time the data is received from the joystick\n\
float32[] axes          # the axes measurements from a joystick\n\
int32[] buttons         # the buttons measurements from a joystick \n\
";
  }

  static const char* value(const ::multijoy::MultiJoy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multijoy::MultiJoy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.njoys);
      stream.next(m.joys);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiJoy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multijoy::MultiJoy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multijoy::MultiJoy_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "njoys: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.njoys);
    s << indent << "joys[]" << std::endl;
    for (size_t i = 0; i < v.joys.size(); ++i)
    {
      s << indent << "  joys[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Joy_<ContainerAllocator> >::stream(s, indent + "    ", v.joys[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIJOY_MESSAGE_MULTIJOY_H
